#!/usr/bin/env python3
"""Build the ClaimTransfer-Bench coverage table.

This is a small reviewer-facing wrapper around ``build_score_report.py``.  It
keeps the paper language concrete: the coverage table is generated by an
official scoring script from released adapter-output rows.
"""

from __future__ import annotations

import argparse
import subprocess
import sys


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", default="claim_records/released_adapter_outputs.csv")
    parser.add_argument("--coverage-out", default="score_reports/coverage_table.csv")
    parser.add_argument("--score-report-out", default="score_reports/score_report.csv")
    parser.add_argument("--claim-record-out", default="claim_records/released_claim_records.csv")
    args = parser.parse_args()

    subprocess.run(
        [
            sys.executable,
            "scripts/build_score_report.py",
            "--input",
            args.input,
            "--coverage-out",
            args.coverage_out,
            "--score-report-out",
            args.score_report_out,
            "--claim-record-out",
            args.claim_record_out,
        ],
        check=True,
    )


if __name__ == "__main__":
    main()
