#!/usr/bin/env bash
set -euo pipefail

# Submit non-KAN hidden/private standard-formula rows on Great Lakes.
#
# This is the companion to submit_claimtransfer_hidden_split_gl.sh, which
# materializes pyKAN hidden claim-card rows.  Here we run non-KAN adapters on a
# maintainer-run hidden/private standard-formula registry with private seed
# blocks.  The formulas are generated by the maintainer harness; official
# scoring later recomputes claim records from raw adapter outputs.
#
# Run from the Great Lakes project root:
#
#   ACCOUNT=jaabell0 STANDARD_ACCOUNT=jaabell0 bash scripts/submit_claimtransfer_nonkan_hidden_gl.sh
#
# Common switches:
#
#   SUBMIT_PYSR=0 bash scripts/submit_claimtransfer_nonkan_hidden_gl.sh
#   SUBMIT_MLP=0 SUBMIT_EQL=0 bash scripts/submit_claimtransfer_nonkan_hidden_gl.sh
#   HIDDEN_ARRAY=0-44 SEEDS_PER_TASK=2 bash scripts/submit_claimtransfer_nonkan_hidden_gl.sh

cd "${SLURM_SUBMIT_DIR:-$PWD}"
mkdir -p logs/greatlakes task_cards

PY="${PYTHON_BIN:-$PWD/.venv/bin/python}"
if [[ ! -x "$PY" ]]; then
  PY="$(command -v python)"
fi

ACCOUNT="${ACCOUNT:-jaabell0}"
STANDARD_ACCOUNT="${STANDARD_ACCOUNT:-$ACCOUNT}"
SPGPU_ACCOUNT="${SPGPU_ACCOUNT:-$ACCOUNT}"
SPGPU_PARTITION="${SPGPU_PARTITION:-spgpu}"

STANDARD_AUGMENT="${STANDARD_AUGMENT:-full}"
TASK_CARDS="${TASK_CARDS:-task_cards/claimtransfer_v1_standard_formula_hidden_private.json}"
TASK_DOC="${TASK_DOC:-task_cards/standard_formula_hidden_private_task_card_map.md}"
TASK_SPLIT="${TASK_SPLIT:-hidden}"
TASK_REGISTRY_VERSION="${TASK_REGISTRY_VERSION:-claimtransfer_v1_standard_formula_hidden_private}"

SEED_BASE="${SEED_BASE:-7000}"
SEEDS_PER_TASK="${SEEDS_PER_TASK:-2}"
HIDDEN_ARRAY="${HIDDEN_ARRAY:-0-29}"
LABEL_PREFIX="${LABEL_PREFIX:-hidden_nonkan}"

SUBMIT_LIGHT="${SUBMIT_LIGHT:-1}"
SUBMIT_GPLEARN="${SUBMIT_GPLEARN:-1}"
SUBMIT_PYSR="${SUBMIT_PYSR:-1}"
SUBMIT_MLP="${SUBMIT_MLP:-1}"
SUBMIT_EQL="${SUBMIT_EQL:-1}"
SUBMIT_SCORE_REFRESH="${SUBMIT_SCORE_REFRESH:-1}"

echo "[$(date -Is)] ClaimTransfer non-KAN hidden submit"
echo "[$(date -Is)] account=${ACCOUNT} standard_account=${STANDARD_ACCOUNT} spgpu_account=${SPGPU_ACCOUNT} partition=${SPGPU_PARTITION}"
echo "[$(date -Is)] python=${PY}"
echo "[$(date -Is)] task_cards=${TASK_CARDS} registry=${TASK_REGISTRY_VERSION} split=${TASK_SPLIT} augment=${STANDARD_AUGMENT}"
echo "[$(date -Is)] seed_base=${SEED_BASE} seeds_per_task=${SEEDS_PER_TASK} array=${HIDDEN_ARRAY}"

"$PY" scripts/generate_standard_formula_task_cards.py \
  --augment "${STANDARD_AUGMENT}" \
  --out "${TASK_CARDS}" \
  --doc "${TASK_DOC}" \
  --split "${TASK_SPLIT}" \
  --registry-version "${TASK_REGISTRY_VERSION}"

COMMON_EXPORT="ALL,PYTHON_BIN=${PY},STANDARD_AUGMENT=${STANDARD_AUGMENT},TASK_CARDS=${TASK_CARDS},TASK_DOC=${TASK_DOC},TASK_SPLIT=${TASK_SPLIT},TASK_REGISTRY_VERSION=${TASK_REGISTRY_VERSION},GENERATE_TASK_CARDS=0,SEED_BASE=${SEED_BASE},SEEDS_PER_TASK=${SEEDS_PER_TASK}"

JOB_IDS=()

submit_job() {
  echo
  echo "+ $*"
  local job_id
  job_id="$("$@")"
  echo "$job_id"
  if [[ -n "$job_id" ]]; then
    JOB_IDS+=("$job_id")
  fi
}

if [[ "${SUBMIT_LIGHT}" == "1" ]]; then
  submit_job sbatch --parsable --account="${STANDARD_ACCOUNT}" --array="${HIDDEN_ARRAY}" \
    --export="${COMMON_EXPORT},LABEL_SUFFIX=${LABEL_PREFIX}_std_s${SEED_BASE}" \
    scripts/greatlakes_standard_formula_adapter_sweep.sbatch
fi

if [[ "${SUBMIT_GPLEARN}" == "1" ]]; then
  submit_job sbatch --parsable --account="${STANDARD_ACCOUNT}" --array="${HIDDEN_ARRAY}" \
    --export="${COMMON_EXPORT},LABEL_SUFFIX=${LABEL_PREFIX}_gplearn_s${SEED_BASE},POPULATION_SIZE=${GPLEARN_POPULATION_SIZE:-600},GENERATIONS=${GPLEARN_GENERATIONS:-20}" \
    scripts/greatlakes_gplearn_standard_formula.sbatch
fi

if [[ "${SUBMIT_PYSR}" == "1" ]]; then
  submit_job sbatch --parsable --account="${STANDARD_ACCOUNT}" --array="${HIDDEN_ARRAY}" \
    --export="${COMMON_EXPORT},LABEL_SUFFIX=${LABEL_PREFIX}_pysr_s${SEED_BASE},NITERATIONS=${PYSR_NITERATIONS:-100},POPULATION_SIZE=${PYSR_POPULATION_SIZE:-64},POPULATIONS=${PYSR_POPULATIONS:-12},PROCS=${PYSR_PROCS:-8}" \
    scripts/greatlakes_pysr_standard_formula.sbatch
fi

if [[ "${SUBMIT_MLP}" == "1" ]]; then
  submit_job sbatch --parsable --account="${SPGPU_ACCOUNT}" --partition="${SPGPU_PARTITION}" --array="${HIDDEN_ARRAY}" \
    --export="${COMMON_EXPORT},LABEL_SUFFIX=${LABEL_PREFIX}_mlphess_s${SEED_BASE},STEPS=${MLP_STEPS:-1800},WIDTH=${MLP_WIDTH:-128},DEPTH=${MLP_DEPTH:-3}" \
    scripts/greatlakes_mlp_hessian_standard_formula_a40.sbatch
fi

if [[ "${SUBMIT_EQL}" == "1" ]]; then
  submit_job sbatch --parsable --account="${SPGPU_ACCOUNT}" --partition="${SPGPU_PARTITION}" --array="${HIDDEN_ARRAY}" \
    --export="${COMMON_EXPORT},LABEL_SUFFIX=${LABEL_PREFIX}_eql_s${SEED_BASE},STEPS=${EQL_STEPS:-2200},UNITS=${EQL_UNITS:-48}" \
    scripts/greatlakes_eql_standard_formula_a40.sbatch
fi

if [[ "${SUBMIT_SCORE_REFRESH}" == "1" ]]; then
  dep_args=()
  if [[ "${#JOB_IDS[@]}" -gt 0 ]]; then
    dep_args=(--dependency="afterany:$(IFS=:; echo "${JOB_IDS[*]}")")
  fi
  submit_job sbatch --parsable --account="${STANDARD_ACCOUNT}" \
    "${dep_args[@]}" \
    --export=ALL,PYTHON_BIN="${PY}",BUILD_FIGURE_SUMMARIES=1 \
    scripts/greatlakes_claimtransfer_score_refresh_standard.sbatch
fi

echo
echo "[$(date -Is)] submitted non-KAN hidden jobs."
if [[ "${#JOB_IDS[@]}" -gt 0 ]]; then
  echo "[$(date -Is)] job ids: ${JOB_IDS[*]}"
fi
echo 'Check with: squeue -u $USER -o "%.18i %.12P %.10a %.30j %.2t %.10M %.10l %R"'
